### PR TITLE
Add Benin

### PR DESCRIPTION
**Pull request by timobleeker**
I've added Benin as a country but please check if I've understood it correctly.

One thing I noticed was that the entity I'm dealing with gave us an IBAN in the format of this example IBAN `BJ66BJ0610100100144390000769`, but that their local number was following the format `01443900007` (11 numbers, counting from the back of the IBAN skipping the last two numbers). So I'm not entirely sure if the local format that this library would convert to is actually correct.

This is from the WIki page linked in the conversion_rules.yml doc:
| Chars | BBAN format | Example |
| ---- | ---- | ---- |
| 28 | 2c, 22n | BJkk ccnn nnnn nnnn nnnn nnnn nnnn |

### CODE REVIEW

**Review by leonardoaretakis — APPROVED** [review]
specs are passing, looks good to me

**Comment by toreriklinnerud** [comment]
@timobleeker Hi thanks for sending the PR. Their IBAN status is listed as experimental, but I figure we can still include it. For the conversation back to the local format I couldn't find any rules beyond what you already added.

**Comment by mateuscruz** [comment]
@toreriklinnerud could you please release this version?

**Comment by mateuscruz** [comment]
@toreriklinnerud bump.

**Pull request merged**
